- .github/workflows/deploy.yml
- package.json
Also had to add in the secrets
- ANSIBLE_VAULT_PASSWORD located in shared password database
- KNOWN_HOSTS generated with `ssh-keyscan -H 51.75.169.235` on the server machine
- SSH_KEY for which I used `ota_org_github_actions` key on server
> Deploy services on server on merge on main branch

- declarations/Airbnb.history.json
- declarations/Airbnb.json
Reverts OpenTermsArchive/services-all#339
OTA-Core errors with
```
Airbnb — Privacy Policy                                 Error: A document content is required
0|ota    |     at Recorder.recordVersion (file:///home/debian/ota/src/archivist/recorder/index.js:65:13)
0|ota    |     at Recorder.recordRefilter (file:///home/debian/ota/src/archivist/recorder/index.js:72:17)
0|ota    |     at Archivist.recordVersion (file:///home/debian/ota/src/archivist/index.js:231:81)
0|ota    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
> Revert "Fix airbnb"

- declarations/Booking.com.filters.history.js
- declarations/Booking.com.filters.js
- declarations/Booking.com.history.json
- declarations/Booking.com.json
> Fix Booking.com by adding non greedy selector to regex

- declarations/Google Play.history.json
- declarations/Google Play.json
This is done to be able to merge https://github.com/OpenTermsArchive/contrib-declarations/pull/378 which has failing tests fixes #490
> Fix Google Play

- declarations/Google Play.filters.js
- declarations/Google Play.history.json
- declarations/Google Play.json
- package-lock.json
- package.json
Make Google Play filters work the same way in node and in browser.
> Move from node-fetch to isomorphic-fetch

- declarations/Airbnb.history.json
- declarations/Airbnb.json
@martinratinaud, could you help me to find the `validUntil` value ? Thx.
> Update Airbnb Privacy Policy

- declarations/Google Play.filters.js
- package.json
Proposal replacement for https://github.com/OpenTermsArchive/contrib-declarations/pull/625. 
Replace deprecated function and remove obsolete dependency and associated code.
> Make google play filters runnable in browser - updated

- declarations/Twitter.filters.js
- declarations/Twitter.history.json
- declarations/Twitter.json
Update to Twitter tos and pp #521 #522 
Taken from recent france-elections-declaration update for Twitter
> Update Twitter tos & pp

- declarations/Reddit.history.json
- declarations/Reddit.json
Fix for Reddit Privacy Policy in  issue #347
> Fix Reddit Privacy Policy and add history.json

- declarations/Facebook.history.json
- declarations/Facebook.json
Hi here is a cleaned up pull request for my recent Facebook fix.
> Fix Facebook blinking

- declarations/Facebook.filters.js
- declarations/Facebook.history.json
- declarations/Facebook.json
> Fix Facebook ToS and PP

- declarations/Facebook.json
- - -
Bots should take care of checking the formatting and the validity of the declaration. As a human reviewer, you should check:
- **stable**: as much as possible, the CSS selectors are meaningful and specific (e.g. `.tos-content` rather than `.ab23 .cK_drop > div`).
- **simple**: the CSS selectors do not have unnecessary specificity (e.g. if there is an ID, do not add a class or a tag).
- **relevant**: it is not just a series of links, for example.
- **readable**: it is complete and not mangled.
- **clean**: it does not contain navigation links, unnecessary images, or extra content.
If no document type seems appropriate for this document yet it is relevant to track in this instance, please check if there is already an [open discussion](https://github.com/ambanum/OpenTermsArchive/discuss …
> Add Facebook Vulnerability Disclosure Policy

- declarations/CommentCaMarche.history.json
- declarations/CommentCaMarche.json
- - -
Bots should take care of checking the formatting and the validity of the declaration. As a human reviewer, you should check:
- **stable**: as much as possible, the CSS selectors are meaningful and specific (e.g. `.tos-content` rather than `.ab23 .cK_drop > div`).
- **simple**: the CSS selectors do not have unnecessary specificity (e.g. if there is an ID, do not add a class or a tag).
- **relevant**: it is not just a series of links, for example.
- **readable**: it is complete and not mangled.
- **clean**: it does not contain navigation links, unnecessary images, or extra content.
Thanks to your work and attention, Open Terms Archive will ensure that high quality data is available for all reusers, enabling them to do their part in shifting the balance of power towards end users and …
> Update CommentÇaMarche Privacy Policy and Terms Of Service

- declarations/Scalingo.history.json
- declarations/Scalingo.json
Here is a new PR to replace [this one](https://github.com/OpenTermsArchive/contrib-declarations/pull/669#event-7603587048) 
Thanks a lot @omjdi for the contribution
> Scalingo's new GTC

- declarations/PayPal.json
> Add PayPal Terms of Service document (EU EN)

- .github/workflows/test.yml
- declarations/OPay.json
- declarations/Paradox Interactive.json
- declarations/Persumi.json
- declarations/Steam.json
- declarations/Tildes.json
- package-lock.json
- package.json
- Add script to start the collection metadata API
- Add linting to test script
- Add a lint step in CI
- Update engine
> Deploy collection metadata API

- declarations/Flutterwave.json
- Create Flutterwave.json
- Track Flutterwave privacy policy
> Add Flutterwave Privacy Policy

- declarations/Stadia.history.json
- declarations/Stadia.json
See their website https://stadia.google.com/gg/
> Stadia was shut down on January 18, 2023.
Fixes #778, #779, #1112, #1113. #1114, #1115
> Terminate Stadia

- declarations/Kraken.history.json
- declarations/Kraken.json
> Fix Kraken TOS declaration

- declarations/Stack Overflow.history.json
- declarations/Stack Overflow.json
> Update Stack Overflow Brand Guidelines declaration

- declarations/Lingualeo.history.json
- declarations/Lingualeo.json
> Fix Lingualeo PP declaration

- declarations/Instacart.history.json
- declarations/Instacart.json
> Fix Instacart Selectors

- declarations/sony.com.history.json
- declarations/sony.com.json
> Fix Sony.com Privacy Policy Selector

- declarations/Parler.history.json
- declarations/Parler.json
> Terminate Parler

- declarations/Alibaba.com.history.json
- declarations/Alibaba.com.json
> Update Alibaba.com declaration

- declarations/Binance.history.json
- declarations/Binance.json
> Fix Binance selectors

- declarations/DeviantArt.history.json
- declarations/DeviantArt.json
> Fix DeviantArt selectors

- config/production.json
From `At minute 30 past every 12th hour` to `At minute 0 past hour 6 and 18`.
> Update tracking schedule

- declarations/Viaplay.json
To celebrate OTA's 4 year anniversary 🎂, I'm adding a few services that I would like to see tracked. 😊
> Add Viaplay

- declarations/Youtube Kids.json
To celebrate OTA's 4 year anniversary 🎂, I'm adding a few services that I would like to see tracked. 😊
> Add Youtube Kids

- declarations/Wix.history.json
- declarations/Wix.json
> Update Wix Terms of Service

- declarations/Criteo.history.json
- declarations/Criteo.json
> Update Criteo Privacy Policy & Criteo Acceptable Use Policy

- declarations/Viaplay.history.json
- declarations/Viaplay.json
> Update Viaplay Privacy Policy

- declarations/Amazon Prime.history.json
- declarations/Amazon Prime.json
> Fix Amazon Prime selector

- declarations/CrowdTangle.history.json
- declarations/CrowdTangle.json
> Update CrowdTangle declarations

- declarations/AdSupply.history.json
- declarations/AdSupply.json
> Update AdSupply declarations

- declarations/Coinbase.history.json
- declarations/Coinbase.json
The new Privacy Policy declaration is fetching correctly locally. The Trackers Policy and Terms of Service are still receiving 403 errors but I did update the declarations as well for when it will be able to fetch again. 
- I selected the "validUntil" date from the first opened issues: #1053 #1054 #1055
> Update coinbase declarations

- declarations/Zora.json
This page could be a new term type: "Summary of Changes" ->  https://support.zora.co/en/articles/1369217
I will open a term types discussion if I find other platforms with the same type of doc.
> Track Zora

- declarations/BBC.history.json
- declarations/BBC.json
> Update BBC Declarations

- declarations/Discord.history.json
- declarations/Discord.json
> Fix Discord declarations

- declarations/Mozilla.history.json
- declarations/Mozilla.json
> Update Mozilla PP declaration

- declarations/PayPal.history.json
- declarations/PayPal.json
> Fix PayPal TOS declaration

- declarations/KICK.json
- declarations/Kick.json
KICK is blocking the contribution tool (see https://social.apreslanu.it/@tk/115060049336481728). Here is my attempt to make the declaration. I wasn't able to work on the selectors yet as I don't have a technical background. @taniki hope this is helpful, @Cli4d do you have time to help with the selectors?
> Add KICK Community Guidelines and Copyright Claims Policy

- declarations/Overleaf.json
Add Overleaf, a popular service for writing documents with LaTeX.
> Add Overleaf

- declarations/Bandcamp.json
> Fix Bandcamp Privacy Policy and add Acceptable Use Policy
