declarations/Instagram.filters.js, declarations/Instagram.history.json, declarations/Instagram.json, declarations/Yuka.filters.js, declarations/Yuka.history.json, declarations/Yuka.json
Fixes #225 and instagram blinking was not yet mentioned as an issue.
I chose to replace the "days ago" by the real date of last modified taken from page metadata, but I'm not sure this should be the way to go.
So feel free to tell me so
=> Update services Yuka and Instagram to remove blinking

.github/workflows/deploy.yml, .github/workflows/test.yml
Like in https://github.com/ambanum/OpenTermsArchive/pull/730, this changeset:
- Relaxes Ansible version constraints and thus fixes [a bug](https://github.com/ansible/ansible/pull/71824) [we encounter](https://github.com/ambanum/OpenTermsArchive/runs/4715351606?check_suite_focus=true) on some deployments.
- Increases readability and maintainability of the CI pipeline.
The `ANSIBLE_VAULT_KEY` secret is defined at organization level so it can be exposed to other repositories that also need it for deployment, like `services-dating`.
I already defined `SERVER_SSH_KEY` in the repository secrets, assuming this PR would get merged. If it does not, this secret should be erased. That key has fingerprint `SHA256:bUADsRkQFPMYMtQrOsoI4GeCxsP3+iDz9x4GiX0IM4k` and is a new one that I added to the …
=> Improve CI and CD

.github/workflows/deploy.yml
Following https://github.com/ambanum/OpenTermsArchive/issues/735, the current CD system would deploy all instances, which luckily fails because the server fingerprints are not all listed.
I added the `--limit` option, which did have the expected impact except that it [initially failed](https://github.com/OpenTermsArchive/services-all/actions/runs/1813906414/attempts/1), then updated the server fingerprint for known hosts in the `SERVER_FINGERPRINT` which [succeeded](https://github.com/OpenTermsArchive/services-all/runs/5113931965?check_suite_focus=true).
=> Deploy continuously

declarations/Instagram.filters.history.js
Necesary after fix of Core.
these tests errors were silently ignored
=> Add missing filters history file for Instagram

declarations/Google Play.filters.js, package.json
The previously used `DataURIParser` is very difficult to get to transpile to browser JS. I tried with both `rollup` and `browserify` setups without any luck.
It seems this package provides little to no addition to a few lines of vanilla JS to handle the data-URI formatting.
Here is a replacement proposal.
=> Make Google Play filters runnable in browser

declarations/Booking.com.filters.js
=> Prevent url with \n from not being recognized

declarations/Instagram.filters.js
To remove the blinking on 
- [Law Enforcement Guidelines](https://github.com/OpenTermsArchive/contrib-versions/commits/main/Instagram/Law%20Enforcement%20Guidelines.md)
- [Community Guidelines](https://github.com/OpenTermsArchive/contrib-versions/commit/526fc195c139ee739e1aa3903ad57c78ea6510ff)
- [Terms of Service](https://github.com/OpenTermsArchive/contrib-versions/commit/11d840df5cbb3d13a3ee81f05b487babd0f476b6)
=> Remove Intagram url param that caused blinking

.github/workflows/test.yml
This will update to the latest version of `open-terms-archive` package and fix the [problem when merging on main](https://github.com/OpenTermsArchive/contrib-declarations/actions/runs/3436321654)
=> Fix OTA scripts as there was an error on merge

package.json
All [newly created PR](https://github.com/OpenTermsArchive/contrib-declarations/actions/runs/3855456615/jobs/6570526346) are failing validation as `ota-validate-declarations: not found`
Changes are copied from [this PR](https://github.com/OpenTermsArchive/pga-declarations/pull/111/files)
=> Fix call to scripts after OTA core update

.github/workflows/test.yml
Follow up on [change deployment PR](https://github.com/OpenTermsArchive/contrib-declarations/pull/748), the `!` pattern seems to [not launch correctly](https://github.com/OpenTermsArchive/contrib-declarations/pull/748/checks) the checks.
So fallback to the `branches-ignore` pattern[ which works](https://github.com/OpenTermsArchive/contrib-declarations/pull/776/checks)
=> Use branches-ignore pattern as ! pattern does not launch action

README.md
Fixes https://github.com/ambanum/OpenTermsArchive/issues/995
=> Move engine reference to new organization

.github/dependabot.yml, README.md
That changeset set up Dependabot to suggest update `@opentermsarchive/engine` automatically.
=> Setup Dependabot

declarations/Polyfill.io.json
Polyfill.io is a large provider for a frontend JavaScript compatibility library. It was sold to a Chinese company on 26/02/2024, opening a security risk on the provider chain. This addition will enable tracking upcoming changes to terms as the events unfold. In particular, the current jurisdiction of arbitration is defined as England.
See https://github.com/polyfillpolyfill/polyfill-service/issues/2834
=> Track Polyfill.io Terms of Services and Privacy Policy

declarations/Alpha Vantage.json
Both URLs respond with a PDF response => no selectors
Uses `?.pdf` as a workaround for lint not supporting arbitrary URLs for PDFs
https://github.com/OpenTermsArchive/engine/issues/900
=> Add 'Alpha Vantage' ToS and PP declarations

declarations/GraphCMS.history.json, declarations/GraphCMS.json, declarations/Hygraph.json
* Rename GraphCMS to Hygraph as per branding change
* Fix Hygraph Privacy Policy and Terms of Service with new URL and selector
See commit descriptions for details.
Replaces my PR #1146, Fixes #1073, #1074
=> Fix GraphCMS/Hygraph Privacy Policy and Terms of Service 

CODE_OF_CONDUCT.md, CONTRIBUTING.md
PR #1151 introduced the `CONTRIBUTING.md` file with a *Read our Code of Conduct* section linking to the invalid URL `https://codeofconduct/`.
I was not able to find any mention of code of conduct documentation or similar on any of
* the docs at https://docs.opentermsarchive.org/
* this repository - README, CONTRIBUTING, or any other obvious file or file with a name including 'conduct' or 'code'
* the demo-declarations repository https://github.com/OpenTermsArchive/demo-declarations (the template for [new] collections)
A comment in the PR #1151 that introduced this reference stated:
> I was unable to locate the code of conduct in the root folder, but I went ahead to send in a PR with placeholder links in order not to drag the draft submission.
It seems like the dead reference and …
=> Drop non-existant code of conduct reference from CONTRIBUTING.md

declarations/Waze.history.json, declarations/Waze.json
Fix for issues #1135 and #1134
=> Update Waze URLs and selectors

declarations/Telegram.json
- Add Telegram Imprint
- Add Telegram Vulnerability Disclosure Policy
- Add Telegram Community Guidelines
- Add Telegram Law Enforcement Guidelines
- Add Telegram Copyright Claims Policy
- Add Telegram Single Sign-On Policy
- Add Telegram Complaints Policy
- - -
Telegram has an unusual layout for its terms. It has dedicated ToS and PP pages, but describes most of its other commitments in a single FAQ, laying out side by side technical, commercial and legal information. This PR implements tracking by identifying specific terms types in rather brittle selectors (as each relies on two named titles), and adds a “catch-all” safety net on the ToS, combining them with the whole FAQ.
The history is not edited as this could have been tracked in the suggested way from the beginning.
=> Track Telegram FAQ and additional terms

declarations/Disqus.filters.js, declarations/Disqus.history.json, declarations/Disqus.json
This was the last correct version before it started blinking. I am not sure where to find the "validuntil" date in this case since it is not an open issue. https://github.com/OpenTermsArchive/contrib-versions/commit/19e76e322f850e0e956cbde12bf5fb5d17712f1e
=> Fix Disqus blinking Privacy Policy

declarations/Gofile.history.json, declarations/Gofile.json
=> Update Gofile declarations

declarations/Wikipedia.history.json, declarations/Wikipedia.json
I am attempting to clean up some of these blinking versions and I noticed that both the TOS and PP for Wikipedia have been blinking for some time. I fixed this by removing the "%" in the translated language section since it changes every time OTA scrapes those pages. 
I was not sure how I should label the `validUntil`  in the history for each but these are the first versions that showed these blinks:
- TOS: https://github.com/OpenTermsArchive/contrib-versions/commit/726c458a6ac7033d2d8dc25968d9ca92c39114c4
- PP: https://github.com/OpenTermsArchive/contrib-versions/commit/4c74db52c91a77d9b1139bcfb07160c76e2bc573
=> Fix Wikipedia blinking

declarations/Coindesk.history.json, declarations/Coindesk.json
I updated Coindesk Terms of Service selectors to reduce cases of blinking in tracking changes. I have not included a history.json file since I am not sure how to get the valid until date, as it is supposed to be the last snapshot time and date, but this service continues its tracking. Maybe you can provide more direction here
=> Update coindesk ToS selector

declarations/Coindesk.history.json, declarations/Coindesk.json
I have updated the Coindesk Privacy policy selector to reduce blinking instances in the tracking.
Note: In didn't add the history file as I don't know how to get the validUntil date
=> Update Coindesk Privacy Policy selector

declarations/Coindesk.history.json, declarations/Coindesk.json
Updated the selector to reduce instances of blinking in the tracking
Note: I haven't added history file as I am unsure in how to best get the validUntil date
=> Update Coindesk Editorial Policy selector

declarations/Lydia.history.json, declarations/Lydia.json
Lydia split into different brands. Seemingly, the Lydia product no longer exists. Sumeria seems to offer a different product called Lydia jackpot or Lydia Paucebook, which is different from the payment app before.
contrib-versions shows Terms broke on 2021-10-27
https://github.com/OpenTermsArchive/contrib-versions/commit/33b5a72eb41f4d756c1c85b3962bcc180f9bc394
Resolves #1290
Resolves #1310
https://techcrunch.com/2024/05/15/lydia-the-french-social-payment-app-with-8-million-users-launches-mobile-banking-app-sumeria/
=> Terminate Lydia service

declarations/Freja eID.json
Freja eID is the official governmental eID in Sweden. Although it's only used by 4% of the population against the private BankID (92%, already added via #1476) ([source](https://svenskarnaochinternet.se/rapporter/svenskarna-och-internet-2024/e-tjanster/#e-legitimation-och-mobilt-bank-id)), it's worth adding as it will probably get more popular and be used in case of digital elections.
=> Add Freja eID
